<?php
require __DIR__.'/includes/config.php';
$products = db()->query("SELECT * FROM products WHERE active=1 ORDER BY id DESC")->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e(APP_NAME)?></title><link rel="stylesheet" href="/assets/style.css"></head><body>
<div class="top">⚡ Cepat • Praktis • Satu tempat untuk kebutuhan digital</div>
<header class="nav"><div class="wrap" style="display:flex;justify-content:space-between;align-items:center;width:100%"><a class="brand" href="/">TEAM<span>87</span> DIGITAL</a><nav class="navlinks"><a href="#layanan">Layanan</a><a href="#produk">Produk</a></nav></div></header>
<section class="hero wrap"><div><span class="pill">PLATFORM DIGITAL SERBA ADA</span><h1>Satu Tempat, Semua <span class="accent">Kebutuhan Digital.</span></h1><p>Isi pulsa, paket data, token PLN, bayar tagihan, diamond game, voucher, dan kebutuhan digital lainnya dari TEAM87 DIGITAL.</p><a class="btn" href="#produk">Mulai Transaksi</a></div><div class="hero-card"><strong>TEAM87</strong><div>Digital Service</div><small style="display:block;margin-top:55px">Store pelanggan + Admin terpisah</small></div></section>
<section id="layanan" class="section wrap"><h2>Layanan Utama</h2><div class="service-grid"><div class="service"><span class="ico">📱</span><b>Pulsa</b><small>Semua operator</small></div><div class="service"><span class="ico">📶</span><b>Paket Data</b><small>Internet</small></div><div class="service"><span class="ico">⚡</span><b>Token PLN</b><small>Listrik prabayar</small></div><div class="service"><span class="ico">🧾</span><b>Bayar Tagihan</b><small>PPOB</small></div><div class="service"><span class="ico">💎</span><b>Diamond Game</b><small>Top up game</small></div><div class="service"><span class="ico">🎮</span><b>Voucher Game</b><small>Produk game</small></div><div class="service"><span class="ico">💳</span><b>E-Wallet</b><small>Isi saldo</small></div><div class="service"><span class="ico">📺</span><b>Voucher Digital</b><small>Produk digital</small></div></div></section>
<section id="produk" class="section wrap"><h2>Produk</h2><div class="products"><?php foreach($products as $p): ?><article class="product"><div><b><?=e($p['name'])?></b><small><?=e($p['category'])?></small><strong><?=money((int)$p['price'])?></strong></div><a class="btn" href="/order.php?id=<?=(int)$p['id']?>">Beli</a></article><?php endforeach; ?></div></section>
<footer class="footer"><div class="wrap"><b>TEAM87 DIGITAL</b><p><?=e(TAGLINE)?></p></div></footer>
</body></html>